# GitHub Labels Configuration
# These labels can be synced using github-label-sync or created manually in GitHub UI

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "feature request"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "enhancement"
  color: "84b6eb"
  description: "Improvement to existing functionality"

- name: "security"
  color: "ee0701"
  description: "Security vulnerability or improvement"

- name: "performance"
  color: "fbca04"
  description: "Performance improvement"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"
