name: ✨ Feature Request
description: Suggest a new feature or improvement for postgres management scripts
title: "[Feature]: "
labels: ["feature request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.
        
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: "e.g., Add support for managing PostgreSQL extensions"
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: "e.g., Currently, there's no easy way to install and manage PostgreSQL extensions through the CLI tool..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "e.g., Add a new 'extensions' command that allows listing, installing, and removing extensions..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "e.g., Manually running SQL commands, using a different tool..."
      
  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you envision using this feature
      placeholder: |
        ```bash
        ./pgctl extensions list
        ./pgctl extensions install pg_trgm
        ./pgctl extensions remove old_extension
        ```
      render: markdown
      
  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component would this feature affect?
      options:
        - Database Management
        - User Management
        - Schema Management
        - Permissions Management
        - CLI/Menu Interface
        - Documentation
        - Other/New Component
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
          required: false
